curator_mongo:
  image: mongo:${MONGO_VERSION}
  container_name: ${PROJECT_NAME}_cdcs_mongo
  restart: always
  environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    - MONGO_INITDB_DATABASE=${MONGO_DB}
    - MONGO_USER=${MONGO_USER}
    - MONGO_PASS=${MONGO_PASS}
volumes:
  - mongo_data:/data/db/
  - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
command: "--auth --noscripting"
networks:
  - internal

networks:
  internal:
    name: deploy_internal
    external: true

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/main-data
      o: bind,nocopy
