[log]
level = "INFO"

[providers.docker]
exposedByDefault = false
endpoint = "tcp://dockerproxy:2375"
network = "traefik"

[providers.file]
directory = "/conf/"

[api]
dashboard = true
debug = false

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.websecure]
address = ":443"

[certificatesResolvers.letsencrypt.acme]
email = webmaster@meta-genome.org <mailto:webmaster@meta-genome.org>
storage = "acme.json"
# caServer = https://acme-staging-v02.api.letsencrypt.org/directory <https://acme-staging-v02.api.letsencrypt.org/directory>

[certificatesResolvers.letsencrypt.acme.httpChallenge]
entryPoint = "http"